version: v1

labels:
  - label: 'ignore-for-release'
    sync: true
    matcher:
      title: '^[vV]?\d+(\.\d+){2}.*'
      body: '#ignore'
  - label: 'breaking-change'
    sync: true
    matcher:
      title: '^.+!:|#breaking'
      body: '## Does this PR introduce a breaking change\?\s+- \[[xX]\] *Yes'
  - label: 'enhancement'
    sync: true
    matcher:
      title: '^[fF]eat.*'
  - label: 'bug'
    sync: true
    matcher:
      title: '^[fF]ix.*'
  - label: 'documentation'
    sync: true
    matcher:
      title: '^[dD](ocs|ocumentation).*'
      files: 'docs/**/*.md'
  - label: 'refactoring'
    sync: true
    matcher:
      title: '^[rR]efactor.*'
  - label: 'test'
    sync: true
    matcher:
      title: '^[tT]est.*'
      files: '**/__tests__/**'
  - label: 'chore'
    sync: true
    matcher:
      title: '^[cC]hore.*'
  - label: 'ci'
    sync: true
    matcher:
      title: '^[cC]i.*'
      files: '.github/**'
  - label: 'ospp'
    sync: true
    matcher:
      baseBranch: '^ospp-\d+\/.*'
  - label: '1.x'
    sync: true
    matcher:
      baseBranch: '^v1\.x'
  - label: 'release'
    sync: true
    matcher:
      baseBranch: '^release\/v2.*'
