changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - allcontributors[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - feature
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - Semver-Patch
        - bug
    - title: Other Changes
      labels:
        - documentation
        - refactoring
        - unit-test
        - ci
