import packageJson from './files/package.json'
import gitignore from './files/.gitignore'
import readme from './files/README.md'
import indexHtml from './files/index.html'
import mainJs from './files/main.js'
import appVue from './files/App.vue'
import manifestJson from './files/manifest.json'
import pagesJson from './files/pages.json'
import uniConfigJs from './files/uni.config.js'
import viteConfigJs from './files/vite.config.js'
import httpJs from './files/src/utils/http.js'
import apiJs from './files/src/api/index.js'
import storeJs from './files/src/store/index.js'
import envJs from './files/src/env.js'
import lowcodeConfigJs from './files/lowcode.config.js'

/**
 * 处理模板中的动态内容
 * @param {string} template 模板字符串
 * @param {Object} schema 应用schema
 * @returns {string} 处理后的模板字符串
 */
function processTemplate(template, schema) {
  if (!template) return ''
  
  // 处理模板中的动态内容，格式为 $$TinyEngine{...}END$
  return template.replace(/\$\$TinyEngine{([\s\S]*?)}END\$/g, (match, expression) => {
    try {
      // eslint-disable-next-line no-new-func
      return new Function('schema', `return ${expression}`)(schema)
    } catch (error) {
      console.error('处理模板动态内容时出错:', error)
      return ''
    }
  })
}

/**
 * 将base64转换为Blob
 * @param {string} base64 base64字符串
 * @returns {Blob} Blob对象
 */
function base64ToBlob(base64) {
  const parts = base64.split(';base64,')
  const contentType = parts[0].split(':')[1]
  const raw = window.atob(parts[1])
  const rawLength = raw.length
  const uInt8Array = new Uint8Array(rawLength)
  
  for (let i = 0; i < rawLength; ++i) {
    uInt8Array[i] = raw.charCodeAt(i)
  }
  
  return new Blob([uInt8Array], { type: contentType })
}

/**
 * 获取UniApp项目模板
 * @param {Object} schema 应用schema
 * @returns {Object} 模板文件映射
 */
export function getTemplate(schema = {}) {
  const { projectName = 'uniapp-project', description = 'UniApp project generated by TinyEngine' } = schema
  
  // 处理package.json
  const processedPackageJson = JSON.parse(
    processTemplate(packageJson, {
      ...schema,
      projectName,
      description
    })
  )
  
  // 返回模板文件映射
  return {
    'package.json': JSON.stringify(processedPackageJson, null, 2),
    '.gitignore': gitignore,
    'README.md': processTemplate(readme, schema),
    'index.html': processTemplate(indexHtml, schema),
    'main.js': processTemplate(mainJs, schema),
    'App.vue': processTemplate(appVue, schema),
    'manifest.json': processTemplate(manifestJson, schema),
    'pages.json': processTemplate(pagesJson, schema),
    'uni.config.js': processTemplate(uniConfigJs, schema),
    'vite.config.js': processTemplate(viteConfigJs, schema),
    'src/utils/http.js': processTemplate(httpJs, schema),
    'src/api/index.js': processTemplate(apiJs, schema),
    'src/store/index.js': processTemplate(storeJs, schema),
    'src/env.js': processTemplate(envJs, schema),
    'lowcode.config.js': processTemplate(lowcodeConfigJs, schema)
  }
}