name: ✨ Feature Request
description: Propose new features to @opentiny/tiny-engine to improve it.
title: '✨ [Feature]: '
labels: ['✨ feature']
body:
  - type: textarea
    id: feature-solve
    attributes:
      label: What problem does this feature solve
      description: |
        Explain your use case, context, and rationale behind this feature request. More importantly, what is the end user experience you are trying to build that led to the need for this feature?
      placeholder: Please Input
    validations:
      required: true
  - type: textarea
    id: feature-api
    attributes:
      label: What does the proposed API look like
      description: |
        Describe how you propose to solve the problem and provide code samples of how the API would work once implemented. Note that you can use Markdown to format your code blocks.
      placeholder: Please Input
    validations:
      required: true
