FROM node:18 as builder
WORKDIR /CODE
ADD . /CODE/

RUN npm install pnpm -g && \ 
    pnpm install && \
    pnpm build:plugin && \
    pnpm build:prod

FROM nginx as RUNNER
COPY --from=builder /CODE/packages/design-core/dist /usr/share/nginx/html
VOLUME [ "/etc/nginx/nginx.conf", "/etc/nginx/conf.d", "/var/log/nginx", "/usr/share/nginx/public/bundle.json"]
EXPOSE 80
