export { default as genDataSourcePlugin } from './genDataSourcePlugin'
export { default as genBlockPlugin } from './genBlockPlugin'
export { default as genDependenciesPlugin } from './genDependenciesPlugin'
export { default as genPagePlugin } from './genPagePlugin'
export { default as genRouterPlugin } from './genRouterPlugin'
export { default as genUtilsPlugin } from './genUtilsPlugin'
export { default as genI18nPlugin } from './genI18nPlugin'
export { default as genTemplatePlugin } from './genTemplatePlugin'
