FROM node:18 as builder
WORKDIR /CODE
ADD . /CODE/

RUN npm install pnpm -g && pnpm install && pnpm build

FROM node:18-alpine as runner
COPY --from=builder /CODE/dist ./dist
COPY --from=builder /CODE/node_modules ./node_modules

ENV DB_URL=""

EXPOSE 9000
CMD [ "node","dist/main.js" ]