export const ComponentName = 'MIframe';

export const EVENT_NAMES = [
    'click',
    'resize',
    'scroll',
    'dblclick',
    'mousedown',
    'mouseenter',
    'mouseleave',
    'mousemove',
    'mouseout',
    'mouseover',
    'mouseup',
    'mousewheel',
    'drag',
    'dragend',
    'dragenter',
    'dragleave',
    'dragover',
    'dragstart',
    'drop',
    'abort',
    'autocomplete',
    'autocompleteerror',
    'blur',
    'change',
    'close',
    'contextmenu',
    'error',
    'focus',
    'keydown',
    'keypress',
    'keyup',
    'load',
    'reset',
]