name: Pull Request Auto Labeler

on:
  pull_request_target:
    types: [opened, edited]

permissions:
  # Setting up permissions in the workflow to limit the scope of what it can do. Optional!
  contents: read # the config file
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # optional, default to '${{ github.token }}'
          config-path: .github/auto-labeler.yml # optional, default to '.github/labeler.yml'
