name: CI

on:
  push:
    branches: []
  pull_request:
    branches: [develop,main]

jobs:
  push-check:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done