name: Push Check

on:
  push:
    branches: []
  pull_request:
    branches: [develop,main]
jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v40
        with:
        files: |
             **.md
             **.js
             **.vue
             **.jsx
          output: all_changed_files
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Run ESLint
        run: npx eslint ${{steps.get_changed_files.outputs.all_changed_files}} --ext .js,.vue,.jsx
      - name: Run Build
        run: pnpm run build:plugin